
name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:

  job_release:
    name: Create Release and Upload to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml

    - name: Install poetry and build wheels
      run: |
        pipx install poetry
        poetry build        

    - name: Create GH release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: dist/*
        draft: true

    - name: Publish to PyPI
      run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
